from matrixa.core import Matrixa

print("matrix with random values")
random_value_mat = Matrixa(3, 3, randomize=True, min_val=10, max_val=20)
print(random_value_mat)

print("--------")

print("matrix with values generated by a function")
def custom_fill(row, col):
    return row + col
mat = Matrixa(3, 3, function=custom_fill)
print(mat)